apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: auchitya-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        command:
        - bash
        - -c
        - |
          unset KAFKA_PORT
          unset KAFKA_PORT_9092_TCP
          unset KAFKA_PORT_9092_TCP_ADDR
          unset KAFKA_PORT_9092_TCP_PORT
          unset KAFKA_PORT_9092_TCP_PROTO
          /etc/confluent/docker/run
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.auchitya-platform.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.auchitya-platform.svc.cluster.local:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: auchitya-platform
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
